### ISSUE TITLE
Coq 8.10+ errors and exits if filename isn't a valid coq identifier

### ISSUE THREAD

**Issue by KevOrr** [ProofGeneral/PG#472] opened 2020-03-23 21:41 UTC
Because PG now uses the `-topfile` argument for recent versions of Coq, file names must now be valid Coq identifiers. For instance, running `proof-goto-point` in a buffer whose file's name is `03-foo.v` will result in coqtop printing and exiting:
```
Error: Invalid character '0' at beginning of identifier "03-foo".
```
Seems to also be an issue in coqide (https://github.com/coq/coq/issues/10988)

https://github.com/coq/coq/issues/10801 suggests using `-top` with a cleaned version of the file name, though I'm not sure what the consequences of that would be.

**Comment by cpitclaudel** [comment] 2020-03-23 21:45
Thanks for the report.  But is there actually a bug to fix? This is a more general problem than with topfile, since a file thus name couldn't be imported, for example.  So erroring out on these files doesn't seem so bad

**Comment by KevOrr** [comment] 2020-03-23 21:56
Seems like a regression because PG + Coq < 8.10 work fine editing and interacting with files whose name contains symbols, start with numbers, or otherwise are not valid identifiers. Personally, not all coq files I create are meant to be imported as part of a larger project; many are just one-off snippets that I name according to the current date (using `open-junk-file`).

That being said, there seems to be no problem editing buffers that are not visiting files (e.g. `*scratch*`), so I'm curious what the differences really are in handling file-visiting and non-file-visiting buffers.

**Comment by hendriktews** [comment] 2020-03-24 13:42
For me this is a new feature or maybe a regression of coqtop. If
coqtop does not accept these file names any more, what could
Proof General do?

**Comment by Matafou** [comment] 2020-03-25 17:24
@hendriktews coqtop does not really know about the file it is running on. It is actually an interactive program reading its standard input. So IMHO it is reasonable to say that it should not fail to start only because of the file name emacs grabs commands from. Cleaning the file name (or removing the -topfile command when the file name is incorrect?) seems a good fix to me.

**Comment by cpitclaudel** [comment] 2020-03-25 21:22
> That being said, there seems to be no problem editing buffers that are not visiting files (e.g. *scratch*), so I'm curious what the differences really are in handling file-visiting and non-file-visiting buffers.

The difference is that we don't pass topfile when we don't have a filename.  I'm not sure what that option does.  We could mangle the name to make it acceptable to coqtop, but it seems weird to embed Coq's naming rules into PG.

**Comment by Matafou** [comment] 2020-03-26 09:32
`coqtop -topfile foo.bar` tells coq that the commands that we send should be considered in a module named foo.bar. The effect of this is that immediately after defining some constant C we can name it foo.bar.C. In coqc the option is not necessary because coqc does know the name of the file it compiles (I don't think it can compile its stdout).

I really think that removing -topfile when the file name is incorrect is OK.

**Comment by Matafou** [comment] 2020-03-26 09:38
To be more precise: `topfile` takes a file name and not a module name. `-topfile foo/bar/file.v` tells coq that the current commands are part of the `foo/bar/file.v` file and coqtop elaborates the module name by itself (looking at -R/-Q options).

**Comment by Matafou** [comment] 2020-03-26 09:39
So as soon as it is clear that the current file does not exist or cannot be compiled because of its name removing the `-topfile` optiob is ok.
I will try yo implement that.

**Comment by cpitclaudel** [comment] 2020-03-26 14:21
> To be more precise: topfile takes a file name and not a module name. -topfile foo/bar/file.v tells coq that the current commands are part of the foo/bar/file.v file and coqtop elaborates the module name by itself (looking at -R/-Q options).

But in that case why doesn't coqtop just issue a warning?

**Comment by Matafou** [comment] 2020-03-26 14:48
I committed a light check on buffer file name disabling the -topfile option if necessary.

**Closed** 2020-03-26 14:47 UTC
