### ISSUE TITLE
PG incorrectly interprets `}.` as a single token, which results in incorrectly accepting files that coqc rejects

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#690] opened 2023-03-05 07:00 UTC
Consider the following file:
```coq
Goal True.
{
exact I.
}.
Qed.
```
Proof General will happily run to the end of the file, with transcript
```
Welcome to Coq 8.16.0

<prompt>Coq < 1 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof".

<prompt>Coq < 2 || 0 < </prompt>Set Suggest Proof Using.

<prompt>Coq < 3 || 0 < </prompt>Set Diffs "off".

<prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 .

<prompt>Coq < 5 || 0 < </prompt>Set Silent.

<prompt>Coq < 6 || 0 < </prompt>Goal True.

<prompt>Unnamed_thm < 7 |branch| 0 < </prompt>{

<prompt>Unnamed_thm < 8 |branch| 0 < </prompt>exact I.

<prompt>Unnamed_thm < 9 |branch| 0 < </prompt>}.

<prompt>Unnamed_thm < 10 |branch| 0 < </prompt>Toplevel input, characters 1-2:
> }.
>  ^
Error: Syntax error: illegal begin of toplevel:vernac_toplevel.

<prompt>Unnamed_thm < 10 |branch| 0 < </prompt>Unset Silent.

<prompt>Unnamed_thm < 12 |branch| 0 < </prompt>Qed.

<prompt>Coq < 13 || 0 < </prompt>
```
I'm guessing the error is not caught by PG because it occurs after `<prompt>`, which happens because `coqtop` interprets `}` as a valid token, but the `.` as invalid.  `coqc` rejects this file with the syntax error

**Comment by Matafou** [comment] 2024-04-03 19:23
Sadly there are quite a few corner cases of pg command detection splitting: #645, #357, #612, #592, #58.
Actually there are two kinds of such limitation: the ones due to notations: PG is not ready for fixing these, and the one that happen in vanilla coq syntax, and we should definitely try to fix them.

**Comment by Matafou** [comment] 2024-04-03 19:25
Duplicate of #357.

**Comment by Matafou** [comment] 2024-04-03 19:26
Closed as a duplicate.

**Closed** 2024-04-03 19:26 UTC
