### ISSUE TITLE
Is `proof-shell-invisible-cmd-get-result' broken in Coq 8.5?

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#19] opened 2015-12-26 11:08 UTC
Hey @Matafou,

Running the following snippet with 8.5 shows the response in the Response buffer for me, and returns the goal as a string.

```
(proof-shell-invisible-cmd-get-result "Extraction nat.")
```

Is that expected? It didn't happen that way in 8.4.

Clément.

**Comment by cpitclaudel** [comment] 2015-12-26 17:22
I think I understand: urgent messages are displayed even for invisible commands. Is that really right? And why is extraction an urgent message?

**Comment by Matafou** [comment] 2015-12-29 15:45
Right. Too much messages are categorized as urgent. I must find another way to display things in response than this one... The problem is that pg display non urgent messages only in particular situations (when displayed after the goal).

I will try to find a fix for this.

**Comment by cpitclaudel** [comment] 2015-12-29 17:00
Thanks Pierre!

**Comment by Matafou** [comment] 2016-01-04 17:12
Should be fixed in coq-8.5 git version. Mad extraction ouput "notice" instead of "info".

**Closed by Matafou** 2016-01-04 17:12 UTC
