### ISSUE TITLE
constant msg: "Zero or more than one goals window, guessing window width."

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#10] opened 2015-11-12 23:52 UTC
I get this msg after every prover step in my minibuffer.  Maybe because I'm running in 3-window mode?

It's a minor annoyance - but makes me wonder if I might see some other useful msgs in the minibuffer if this one wasn't there all the time.

-- Jonathan

**Comment by cpitclaudel** [comment] 2015-11-13 00:10
I think this is connected to Pierre's recent change that sets the printing with dynamically. @Matafou, do you know where this could come from?

**Comment by cpitclaudel** [comment] 2015-11-13 00:11
@jonleivent, I don't get this message while running in three-windows mode; only if I close the goal window.

**Comment by cpitclaudel** [comment] 2015-11-13 00:12
Btw, are you running company-coq? It does manipulate the window configuration, so it could be contributing to the problem.

**Comment by jonleivent** [comment] 2015-11-13 00:24
No, not running company-coq.  But I've heard good things about it... :)

My 3-windows mode is configured in "smart" layout mode - and I arrange all 3 windows to be max vertical size and default width - which means one has to be partially buried on my monitor - and I do that to the *response* window (which is at the left side of the screen, with its right side buried under the source window).  The *goals* window is at the right side of the screen.

The msg appears even when there are no goals - as when executing a command at top-level in the source window.

**Comment by Matafou** [comment] 2015-11-13 00:35
Mmmh not totally understood your buffer layout. Is it separate frames (= X
windows in emacs jargon)? I will check the behavior when frames are
separate. I can also remove the warning.

This message appears when pg tries to compute the width of goals buffer (to
set the printing width) and finds either zero window currently displaying
goals buffer (or more than one).

P.



2015-11-13 1:24 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by jonleivent** [comment] 2015-11-13 00:37
Yes - separate frames (else partial burying would not be possible).

**Comment by cpitclaudel** [comment] 2015-11-13 04:29
Ok, reproduced with multiple frames; I've pushed a tentative fix. @jonleivent, can you try it out?

**Comment by cpitclaudel** [comment] 2015-11-13 04:34
Btw @Matafou, I'm not sure I follow the logic of that bit of code too well. Shouldn't we just return nil if we can't find the goals window, instead of using the currently selected window?

Also, could we inline `coq-ask-adapt-printing-width-and-show` in the `interactive` spec of one of the other functions?

**Comment by Matafou** [comment] 2015-11-13 10:06
2015-11-13 5:34 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

> Btw @Matafou <https://github.com/Matafou>, I'm not sure I follow the
> logic of that bit of code too well. Shouldn't we just return nil if we
> can't find the goals window, instead of using the currently selected window?
>

In any case the message should be a debug only warning.

You are maybe right but we have a small glitch when no goal buffer is
visible: when the buffer pops up againit means that coq has displayed (a
new goal) with the width set *before* it poped up. So ideally we need to
guess the correct width before it pops up.

I fallback to current buffer width because it has a chance to be a good
guess: If the goal buffer is not visible it will probably pop up by
splitting the current buffer at the next goal change, hopefully the split
is vertical and the guess is ok. But of course it works only for 1 frame
mode + 3 windows mode. We should guess something else in other modes. And
this is still a bit fragile. Since a lot of people use the same width for
the 3 buffers it is statistically not so bad but may end up doing strange
things in some cases.

In 2 windows mode (1 or more frames) actually we should first look at the
width of response buffer if goals one is not visible, since the goals
buffer will display there next time.

This heuristic should be in another function anyway.

Also, could we inline coq-ask-adapt-printing-width-and-show in the
> interactive spec of one of the other functions?
>
Indeed we could, please do.

**Comment by Matafou** [comment] 2015-11-13 13:54
Just made some experiments.

Actuallywhen the goals buffer is really invisible things are really a mess (it sometimes hides the scripting buffer...) So no real point now in guessing anything. I will commit a cleaner version with less guessing and a debug warning (that won't display in normal session).

**Comment by Matafou** [comment] 2015-11-13 15:40
Done.  Closing the bug, but we still need to think about width guessing.

**Comment by cpitclaudel** [comment] 2015-11-18 15:49
I don't understand this part in `coq.el`:

```
;; this initiates aut adapt printing width at start, by reading the config var.
;; Let us put this at the end of hooks to have a chance to read local variables
;; first.
(add-hook 'coq-mode-hook 'coq-auto-adapt-printing-width-switch t)
```

Is this a accidental leftover? That function doesn't seem to be defined.

**Comment by Matafou** [comment] 2015-11-23 10:08
Yes, indeed it is a typo. I will fix this.
P.

2015-11-18 16:49 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment] 2015-11-23 12:21
Thanks! Or just point me to the right function and I'll push the fix :)

**Comment by jonleivent** [comment] 2015-11-25 19:16
I think there's still an issue here.  Although I no longer get those "Zero or more than one goals window, guessing window width." messages, I can't seem to get "Set Printing Width" to take hold.

My configuration is: 3 windows, 3 frames.  The source and goal frames are both set to the default width (about 80 chars).  The response frame is set to be 100 chars wide - so that I can do extractions and get something more easily readable.   I do a "Set Printing Width 100" and everything that prints during the same interaction does get to be 100 wide.  But things are reset to 80 on the next interaction.

Maybe this is too much to ask: that the 3 separate frames all have 3 distinct widths?  It's really because of the frequency with which I do extractions (after most function definitions) that I want the response frame both separate and wider than the source and goals frames.  Is there another way to do this?

My ideal environment would have a separate extraction on-the-fly window, so that one can both see the current goals and the corresponding unfinished OCaml code (with holes - like Agda or Idris).  I know this is a rather strange request, though.  Probably not many who program-by-proving, and thus like to see both the current goals and the corresponding unfinished extracted code.

**Comment by Matafou** [comment] 2015-11-26 15:56
Indeed currently the width is automatically computed from the buffer
currently displaying the goal, which is probably what most people want. In
your case however it is not what you want.

As a workaround you should simply deactivate auto width completely for now.

Coq displays glued goals and responses after one single command, so
currently we cannot set the width separately.

P.


2015-11-25 20:16 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by jonleivent** [comment] 2015-11-27 03:39
How do I deactivate auto width completely?

**Comment by cpitclaudel** [comment] 2015-11-27 11:50
@jonleivent I think it's in `coq-auto-adapt-printing-width`

**Comment by Matafou** [comment] 2015-11-27 13:19
Yes.
P.

**Comment by jonleivent** [comment] 2015-11-27 15:32
Strange behavior with coq-auto-adapt-printing-width:  I see that it appears in the Options->Customize Emacs interaction as "Coq Auto Adapt Printing Width" - but when I set it there and apply-and-save the changes, nothing gets written to my .emacs, and there is no impact on the behavior.

So, I instead directly edited by .emacs file to have '(coq-auto-adapt-printing-width nil) in the custom-set-variables list.  That appears to work.

**Comment by Matafou** [comment] 2015-12-04 10:54
Sorry for the delay, it is fixed now.
P.

2015-11-23 11:07 GMT+01:00 Pierre Courtieu <pierre.courtieu@gmail.com>:

**Comment by Matafou** [comment] 2015-12-04 10:59
I don't know if my fix about coq-auto-adapt-printing-width-switch is
related (probably not), but when I use customize + "apply and save" I do
see the .emacs writen with a new line  '(coq-auto-adapt-printing-width nil).

Do you still have this strange behavior?

P.

2015-11-27 16:32 GMT+01:00 Jonathan Leivent <notifications@github.com>:

**Comment by jonleivent** [comment] 2015-12-04 16:22
Your latest changes appear to have fixed the problem with apply-and-saving this option.

**Comment by Matafou** [comment] 2015-12-04 17:13
Great.

**Closed by Matafou** 2015-12-04 17:13 UTC
