### ISSUE TITLE
Indentation of ssreflect's `by`

### ISSUE THREAD

**Issue by proux01** [ProofGeneral/PG#580] opened 2021-06-03 14:25 UTC
In ssreflect, the `by` tactic is used like `now` in ltac. Thus, it would be nice to avoid indenting by when it starts a tactic.

I currently have this in my .emacs
```
'(coq-smie-user-tokens (quote (("by" . "now"))))
```
to alway indent `by` as `now` but it's not fully satisfying.

**Comment by Matafou** [comment] 2021-06-07 07:46
Thanks for reporting. I am currently rewriting the indentation engine, so I will try to take this into account.
Problem here is that, as many other keywords, "by" is used at different places in the grammar.

assert (...) by auto.
Add Morphism.... reflexivity proved by foo.
by tac.

So to indent the former one I need to detect each use of "by".

**Comment by erikmd** [comment] 2021-06-07 12:29
@Matafou Does it help to note that the only `by` mentioned Pierre (the ssreflect one) is always a beginning of a tactic?
I mean, the following is OK, no indentation issue here:
```coq
assert (H : True).
  by exact I.
```
while scripts like
```coq
simpl.
  by etc.
(* or *)
simpl;
  by etc.
```
are the only scripts wrongly intended currently − should be:
```coq
simpl.
by etc.
(* or *)
simpl;
by etc.
```
Finally do you have some feedback on the suggestion by Pierre involving `coq-smie-user-tokens`?
because FTR, `by` is **exactly** the ssreflect counterpart of `now`, so maybe that solution would suffice?

**Comment by erikmd** [comment] 2021-06-07 12:34
Sorry @Matafou, on second thought I realize you had already addressed my questions in your comment!

So indeed if relying on `coq-smie-user-tokens` just sounds like a workaround, it'd be required to

> detect each use of "by"…

**Comment by Matafou** [comment] 2021-06-07 13:55
Sorry but I don't see the bug. More precisely:
I get this indentation
```coq
simpl.
by etc.
```
I don't see an space before the `by` here. 
And I consider this
```coq
simpl;
  by etc.
```
correctly indented (and it has nothing to do with `by`). IMHO it is a feature that the first newline in a sequence of `;` gives one level of indentation.

Otherwise it would be difficult to distinguish:
```coq
a very long; an composed; tactic;
and; its neighbor.
```
from
```coq
a very long; an composed; tactic.
and; its neighbor.
```
Note that there is a subtlety here: this level of indentation only happens at toplevel, for instance here there is no such indentation after the first `;`, because there is no need to distinguish from `.`.:
```coq
repeat(
  a very long; an composed; tactic;
  an its neighbor).
```

**Comment by proux01** [comment] 2021-06-07 15:04
Here is an example:
```Coq
Require Import ssreflect.

Goal True -> True.
Proof.
move=> _.
  by [].
Qed.
```
I would expect:
```Coq
move=> _.
by [].
```

**Comment by erikmd** [comment] 2021-06-07 16:09
Indeed, thanks @proux01.

And note that the issue arises whatever is the value of `coq-indent-proofstart` − by default, 2:
```coq
Goal True -> True.
Proof.
  move=> _.
    by [].
Qed.
```
and with `(setq coq-indent-proofstart 0)`:
```coq
Goal True -> True.
Proof.
move=> _.
  by [].
Qed.
```

regarding the second point, you're absolutely right, @Matafou: there was no issue there, with a semicolon:
```coq
simpl;
  by etc.
```

**Comment by erikmd** [comment] 2021-06-07 16:13
While we are on it, when we take the script `move=> _. by [].` and replace the first dot with a (semicolon, newline) we get a weird indentation:
```coq
move=> _;
         by []. (* this should only be 2-space indented *)
```
albeit this seems **unrelated to `by`**:
```coq
move=> _;
         []. (* this should only be 2-space indented *)
```
but rather related to the `=>` tactical… @Matafou, feel free to ask if you'd want we open another issue for that one…

**Comment by Matafou** [comment] 2021-06-08 08:07
```
Proof.
move=> _.
  by [].
```
True, this is a bug. Don't know why I couldn't reproduce. It seems fixed in my current reimplementation though.
```
move=> _;
         done.
```
This one too. Once again a token ("=>") reused in the grammar... Sigh. This one is not fixed in my current work.
Thanks!  I hope to push my reimplementation soon, I am in trying to make things robust so please keep on filling bug reports.

**Comment by Blaisorblade** [comment] 2021-08-15 11:29
Is #453 a duplicate?

**Comment by proux01** [comment] 2021-08-15 14:05
Indeed, let's close this one then.

**Closed** 2021-08-15 14:05 UTC
