### ISSUE TITLE
Release 4.5

### ISSUE THREAD

**Issue by xgqt** [ProofGeneral/PG#637] opened 2022-01-28 11:05 UTC
Proofgeneral's version is described in the "README" as 4.5-git and last release, 4.4 was in 2016, 
some system distributions are still on 4.4. 
I think it would be good to make a new release after ~5 years and theoretically let distribution maintainers know that they should update their packages.

Repology report of Proogneral for reference: https://repology.org/project/proofgeneral/versions

**Comment by Matafou** [comment] 2022-02-01 11:41
Hi! Actually PG is now proposed as an emacs package. @xgqt what do you think we should do?

- Ask for PG removal from distros and let people use emacs package system?
- Ask the distros to install PG via emacs packages (is it possible/a good idea?)?
- Make releases anyway?

@monnier do you have any advice on this subject?

**Comment by monnier** [comment] 2022-02-01 13:47
Pierre Courtieu [2022-02-01 03:41:46] wrote:
> Hi! Actually PG is now proposed as an emacs package. @xgqt what do you think we should do?
> - Ask for PG removal from distros and let people use emacs package system?
> - Ask the distros to install PG via emacs packages (is it possible/a good idea?)?
> - Make releases anyway?
> @monnier do you have any advice on this subject?

The ELPA system was designed from the beginning to accommodate
system-installed packages, so most distributions like Debian are very
happy to package ELPA packages (`aptitude search '^elpa-' | wc` suggests
there are more than 300 of them in Debian): it actually makes things
easier for them since those are "pre-packaged" to some extent.

So, just don't worry about distros.

**Comment by Matafou** [comment] 2022-02-01 14:02
> So, just don't worry about distros.

Great! But we can still ping them so that they know they should modify their PG package to be elpa, don't we?

**Comment by monnier** [comment] 2022-02-01 14:35
> Great! But we can still ping them so that they know they should modify their
> PG package to be elpa, don't we?

Of course.

**Comment by xgqt** [comment] 2022-02-01 15:40
> Make releases anyway?

Even NPM packages that probably nobody packages in distributions because of microdependencies make tags/releases.

**Comment by erikmd** [comment] 2022-02-09 16:55
Hi all, indeed, we just had a PG maintainer telco and we agree to push tags more frequently in the future (which will also be compatible with MELPA stable).
So, we'll try our best to start this at our next meeting.

**Comment by xgqt** [comment] 2022-02-09 16:58
> Hi all, indeed, we just had a PG maintainer telco and we agree to push tags more frequently in the future (which will also be compatible with MELPA stable). So, we'll try our best to start this at our next meeting.

Nice! Thanks in advance.

**Comment by erikmd** [comment] 2022-07-14 11:49
FYI @xgqt (Cc @ProofGeneral/core): as a follow-up of the very last PG maintainer telco, we tagged proof-general [`v4.5`](https://github.com/ProofGeneral/PG/releases/tag/v4.5).

So I believe we can close this issue now.

(But we still need to prepare some announcement though, to recap all the changes brought by this version.)

**Closed by erikmd** 2022-07-14 11:49 UTC
Labels: kind: question

**Comment by xgqt** [comment] 2022-07-14 11:50
@erikmd Thanks a lot for info!

**Comment by erikmd** [comment] 2022-07-14 11:54
@xgqt Thanks to you! − and sorry for the time it took for us to release this version…
