### ISSUE TITLE
PG accepts `}.` but `coqc` doesn't

### ISSUE THREAD

**Issue by samuelgruetter** [ProofGeneral/PG#592] opened 2021-08-03 17:31 UTC
I can step through the following file in proof general without getting any errors:

```coq
Goal True /\ True.
Proof.
  split.
  { exact I. }.
  { exact I. }.
Qed.
```

However, when I try to compile it with `coqc`, I get
```
File "./PG_close_brace_dot.v", line 4, characters 14-15:
Error: Syntax error: illegal begin of vernac.
```

This breaks the invariant that PG should accept a file iff `coqc` accepts it.

Coq version: 8.13.2
PG version: master (bc86736abb728ec0d28abc90ef0adae21d29a66a)

**Comment by Matafou** [comment] 2021-08-04 07:45
Well spotted. Will try to fix this during summer.

**Comment by Matafou** [comment] 2024-04-03 19:28
Duplicate of #357.

**Closed by Matafou** 2024-04-03 19:28 UTC
