### ISSUE TITLE
Proof General automatically resizes goals/response windows between proof steps

### ISSUE THREAD

**Issue by fidget324** [ProofGeneral/PG#56] opened 2016-02-19 20:30 UTC
In any coq proof script, whenever I step through a proof in three-window mode, the goal and response windows automatically resize. More specifically, the response window shrinks/expands to fit whatever text it is showing, and thus the goals window expands/shrinks accordingly. Based on my understanding of the proof-three-window-enable option (which I have enabled), this behavior should not occur:

"Setting this option triggers a three-buffer mode of interaction where the goals buffer and response buffer are both displayed, rather than the two-buffer mode where they are switched between. It also prevents Emacs automatically resizing windows between proof steps."

I can always get back to the original window positions by hitting ^C^L.

My software platform:
OSX 10.11.3
Aquamacs 3.2
PG 4.4pre (updated 2/19/2016, installed through homebrew)
Coq 8.5 (installed through homebrew)

**Comment by fidget324** [comment] 2016-02-19 20:38
By the way, I was also able to confirm this same behavior in the terminal with Emacs 24.5.1.

**Comment by cpitclaudel** [comment] 2016-02-19 21:49
With these extra details, this sounds like a documentation bug, more than a PG bug; the auto-resizing is on purpose, though it happens only (I believe) in mixed mode (that is, with goal and response stacked). If you use three columns, there will be no resizing, I think.

Why do you not want resizing to happen?

**Comment by Matafou** [comment] 2016-02-20 09:43
I confirm what Clement said: this is on purpose if goals and response
buffers are stacked.
Why is it a problem?
P.

**Comment by Matafou** [comment] 2016-02-20 09:46
Oh does Pg resize "X" Windows (I.e. Emacs frames)?
That would be a bug.

Le samedi 20 février 2016, Pierre Courtieu <pierre.courtieu@gmail.com> a
écrit :

> I confirm what Clement said: this is on purpose if goals and response
> buffers are stacked.
> Why is it a problem?
> P.
>
> Le vendredi 19 février 2016, Clément Pit--Claudel <

**Comment by fidget324** [comment] 2016-02-20 15:20
Pierre and Clément,

PG is resizing emacs frames. Perhaps this is the right behavior; I just
found it bothersome because the behavior of CoqIDE is to fix the size of
the goal and response windows.

~Scott

**Comment by cpitclaudel** [comment] 2016-02-21 03:50
Hi Scott. I'll close this issue then (IIUC PG is resizing Emacs windows, not Emacs frames); it's indeed expected that the goal and response windows will be auto-resized when they are stacker. Let me know of you want help turning off that behaviour, of course :) But I recommend trying it out; I for one do like it quite a bit :)

Also (shameless self advertisement), if you're trying out IDEs for Coq, you may want to try my PG plug in, [company-coq](https://github.com/cpitclaudel/company-coq/).

**Comment by fidget324** [comment] 2016-02-21 19:41
Clément,

Thanks for the help (and the pointer to company-coq), but I do still
believe there is a bug. The window resizing was annoying me because it was
consistently chopping off text in the response window, i.e. the response
window was never growing large enough to encapsulate even just a few lines
of text. I believe the reason is that I use large fonts, e.g. 18 point, in
all of my emacs windows. When I switch to a 12 point font, the response
window always resizes correctly. Also, it seems that PG does not generate
sensible line breaks in responses when the font is larger than 12 points.
For instance, I can type "Check even_list_ind." and get the following
response in 12 point monaco font from coq (I added the line numbers for
reference):

1 even_list_ind
2      : forall P : even_list -> Prop,
3        P ENil ->
4        (forall (n : nat) (o : odd_list), P (ECons n o)) -> forall e :
even_list, P e

and the response window grows to encapsulate all of the text. However, when
I change to 18 point font I get:

1 even_list_ind
2      : forall P : even_list -> Prop,
3        P ENil ->
4        (forall (n : nat) (o : odd_list), P (ECons n o)) ->
forall e : even_list, P e

This time, coq did not produce a line break after the "->" in line 4, so
the text wrapped onto the next line of the output. Moreover, the bottom of
the output is cut off halfway through line 4, so I need to scroll down to
read the rest of the type.

Would you agree that this is a bug?

~Scott

**Comment by cpitclaudel** [comment] 2016-02-22 00:38
@fidget324 Indeed, this doesn't look too great. How are you setting the font size?

**Comment by fidget324** [comment] 2016-02-22 00:42
I'm using the OSX Aquamacs GUI. From the response window, I navigate to Options -> Appearance -> Font for Coq-Response-Mode...

Thanks for looking into this!

**Comment by cpitclaudel** [comment] 2016-02-22 01:12
Ah, of course. Aquamacs uses a `font-remapping-alist` entry, which is hard to take into account properly.

The problem is that we (probably) compute the window width as `number of lines * height of a single line`. The second term here is computed wrt to the default font, not the one that Aquamacs sets up, because aquamacs abuses the `font-remapping` mechanism to produce per-mode fonts.

I'm not too too inclined to spend a lot of time debugging Aquamacs specific issues, given the lengths that Aquamacs goes to to make the life of Emacs packages maintainers harder. Still, I'll try to have a look at it soon, if I can find the time. @fidget324, would you be ok to test a patch if I write one (I don't have a mac, so I can test myself)?

@Matafou: if you want to look into this, the trick would probably be to use window-text-pixel-size to measure the size of the response. This would work for the window resizing; for the window width, I'm not sure what we can do.

**Comment by cpitclaudel** [comment] 2016-02-22 01:25
Some more details: the issue with incorrect wrapping is due to the fact that we automatically send `Set Printing Width` to Coq, so that things wrap properly. We compute the width in terms of numbers of columns, but aquamacs doesn't adjust that when setting the font size through `face-remapping-alist`

**Comment by cpitclaudel** [comment] 2016-02-22 01:27
@fidget324 Do you use the same font size in every window? If so, using a different mechanism to set the font size will solve these two problems (and many others).

**Comment by fidget324** [comment] 2016-02-22 01:57
@cpitclaudel I fixed it. The solution was to set the default font for Aquamacs as in the Aquamacs FAQ:

"To set the default font for all buffers, use emacs face customization menu: `M-x customize-face` and type in `default`. Then place the cursor in the `Font Family` input area and type in a new font family name, e.g. `apple-bitstream vera sans mono`. Click `Save for Future Sessions` and `Finish`."

Then for each buffer, I navigated to Options -> Appearance -> Auto Faces -> Apply Face of Some Mode -> Default. Now the response window is resizing properly, and line breaks are also being inserted correctly :).

@cpitclaudel if you still would like to test a patch for the font remapping behavior of Aquamacs, I would be willing to test it for you, but this fix also works just fine.

**Comment by cpitclaudel** [comment] 2016-02-22 02:33
Great, this was just the solution I was alluding to. This sidesteps `face-remapping-alist` entirely, and is the proper way to set the default size :)

I'll close this then; we can revisit the issue for more specific cases if it pops up again.

Thanks for all the feedback, by the way! These discussions quickly get technical, but do we love getting feedback, especially from users who are not yet used to Proof General. Many thanks :)

**Closed by cpitclaudel** 2016-02-22 02:33 UTC

**Comment by Matafou** [comment] 2016-02-27 19:33
Thanks for fixing this Clement and Scott.

Let us put some information somewhere about this.
P.
