### ISSUE TITLE
Hitting 'tab' to indent just throws an error

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#677] opened 2022-11-14 17:58 UTC
After just updating ProofGeneral, auto-indentation is no longer working. When I hit 'tab', I just get an error in the status buffer:
```
Error: (void-variable x)
```
I don't know how to capture any better error information... this happens no matter where I try it, across all projects. For example I tried [this line](https://gitlab.mpi-sws.org/iris/iris/-/blob/c9b39944a7e6ce1b30217183240b00a063a10c13/iris/algebra/cmra.v#L12).

Here are some potentially relevant parts of my .emacs. This exact configuration worked fine before the update.
```
;; Custom (managed) Settings
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-font-list
   '((1 "\\alert{" "}" "\\mathcal{" "}")
     (2 "\\textbf{" "}" "\\mathbf{" "}")
     (3 "\\textsc{" "}")
     (5 "\\emph{" "}")
     (6 "\\textsf{" "}" "\\mathsf{" "}")
     (9 "\\textit{" "}" "\\mathit{" "}")
     (13 "\\textmd{" "}")
     (14 "\\textnormal{" "}" "\\mathnormal{" "}")
     (18 "\\rstinline{" "}")
     (19 "\\textsl{" "}" "\\mathbb{" "}")
     (20 "\\texttt{" "}" "\\mathtt{" "}")
     (21 "\\textup{" "}")
     (4 "" "" t)
     (16 "\\PRES{" "}")))
 '(TeX-PDF-mode t)
 '(TeX-auto-save t)
 '(TeX-insert-braces nil)
 '(TeX-parse-self t)
 '(TeX-source-correlate-mode t)
 '(TeX-source-correlate-start-server t)
 '(TeX-view-program-list
   '(("Evince" "/home/r/bin/evince --page-index=%(outpage) %o")))
 '(column-number-mode t)
 '(compilation-scroll-output 'first-error)
 '(coq-compile-before-require t)
 '(coq-compile-parallel-in-background t)
 '(coq-compile-quick 'no-quick)
 '(coq-compile-vos 'vos)
 '(coq-one-command-per-line nil)
 '(default-input-method "math")
 '(desktop-path '("." "~/.emacs.d/" "~"))
 '(desktop-save 'if-exists)
 '(desktop-save-mode t)
 '(electric-indent-mode nil)
 '(fill-column 80)
 '(font-use-system-font t)
 '(global-auto-revert-mode t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(make-backup-files nil)
 '(mf-display-padding-height 75)
 '(package-selected-packages
   '(undo-tree ripgrep racer rust-mode f yasnippet maxframe math-symbol-lists markdown-mode dash column-marker auctex))
 '(preview-auto-cache-preamble t)
 '(preview-default-preamble
   '("\\RequirePackage["
     ("," . preview-default-option-list)
     "]{preview}[2004/11/05]" "\\PreviewEnvironment{mathparpagebreakable}"))
 '(preview-scale-function 1.4)
 '(proof-follow-mode 'followdown)
 '(proof-next-command-insert-space nil)
 '(proof-omit-proofs-configured t)
 '(proof-omit-proofs-option t)
 '(proof-splash-enable nil)
 '(proof-three-window-enable t)
 '(proof-three-window-mode-policy 'hybrid)
 '(reftex-plug-into-AUCTeX t)
 '(safe-local-variable-values '((reftex-default-bibliography "n.bib" "p.bib")))
 '(sentence-end-double-space nil)
 '(show-paren-mode t)
 '(standard-indent 4)
 '(tab-stop-list '(4 8))
 '(tool-bar-mode nil))


;; Coq
(load "~/src/coq/ProofGeneral/generic/proof-site.el")
(add-hook 'coq-mode-hook (lambda () (interactive) (column-marker-1 80)))
(add-hook 'coq-mode-hook (lambda () (undo-tree-mode 1)))
(setq coq-smie-user-tokens
   '(("," . ":=")
	("∗" . "->")
	("-∗" . "->")
	("∗-∗" . "->")
	("==∗" . "->")
        ("=∗" . "->") 			;; Hack to match ={E1,E2}=∗
	("|==>" . ":=")
	("⊢" . "->")
	("⊣⊢" . "->")
	("↔" . "->")
	("←" . "<-")
	("→" . "->")
	("=" . "->")
	("==" . "->")
	("/\\" . "->")
	("⋅" . "->")
	(":>" . ":=")
	("by" . "now")
	("forall" . "now")              ;; NB: this breaks current ∀ indentation.
   ))
```

**Comment by RalfJung** [comment] 2022-11-14 19:57
Before the update, I was on commit fd04605a.
Now I updated to d1bbf22e.

**Comment by Matafou** [comment] 2022-11-28 10:55
Hi Ralf,
I can't reproduce. Please can you provide:
- the value of your ` package-archives`
- the command run by tab: i.e. the result of `M-: ((lookup-key (current-global-map) (kbd "TAB"))`.
- try to reproduce the bug with an empty emacs config:
```bash
emacs -q -no-site-file -l ~/.emacs.d/elpa/proof-general-XXXXXXX/generic/proof-site.el  foo.v
```

**Comment by RalfJung** [comment] 2022-11-29 15:50
> the value of your package-archives

Eh... what is that?^^ I have this at the top of my .emacs file, maybe that is what you mean:

```
;; MELPA
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
```

However, PG is not installed via MELPA, I am installing it from source and then importing with the snippet I showed above.

> the command run by tab: i.e. the result of M-: ((lookup-key (current-global-map) (kbd "TAB")).

This says "End of file during parsing"... I guess I did something wrong? Parentheses do not seem balanced though. Adding another closing paren I then get
```
Debugger entered--Lisp error: (invalid-function (lookup-key (current-global-map) (kbd "TAB")))
  ((lookup-key (current-global-map) (kbd "TAB")))
  eval(((lookup-key (current-global-map) (kbd "TAB"))) t)
  eval-expression(((lookup-key (current-global-map) (kbd "TAB"))) nil nil 127)
  funcall-interactively(eval-expression ((lookup-key (current-global-map) (kbd "TAB"))) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

> try to reproduce the bug with an empty emacs config:

I get the same error there (using `emacs -q -no-site-file -l ~/src/coq/ProofGeneral/generic/proof-site.el /tmp/test.v`).

**Comment by RalfJung** [comment] 2022-11-29 15:51
So maybe something is wrong with my build-from-source?  I tried `git clean -fx`, and then `make -j8` again -- and now it works again. :) Usually I do `git pull && make -j8`; looks like the build is not safe against still having artifacts from previous builds lying around somewhere.

**Comment by Matafou** [comment] 2022-11-29 16:19
OK. Thanks for the feedback. Sorry my lisp snippet was indeed ill-formed. It is a bit disturbing that you needed `make clean`. Let us close this anyway...
Note: If you don't intend to hack in pg, then you should probably consider using the melpa package.

**Closed by Matafou** 2022-11-29 16:19 UTC

**Comment by RalfJung** [comment] 2022-11-29 16:27
> Note: If you don't intend to hack in pg, then you should probably consider using the melpa package.

Yeah... but "never touch a running system"...^^
