### ISSUE TITLE
Stuck with proof of software foundations.

### ISSUE THREAD

**Issue by mukeshtiwari** [ProofGeneral/PG#83] opened 2016-06-30 07:29 UTC
I am facing a very bizarre problem and sorry for this big post. I am going through Induction chapter of software foundations [1] using Coq 8.5pl1. I have written the proof of multiplication is commutative in line 115 - 133. I finished the proof and moved to next proof leb_refl. After finishing the leb_refl I thought about changing couple of things in mult_comm in line 128. Following the required change I pressed Ctrl-c Ctrl-return but it got stuck at reflexivity in line 120. I erased the whole line 120 and rewrote the same thing again, and it worked perfectly fine. The only problem occurred when I changed some thing in middle of mult_comm proof and hit C-c C-return, so I commented the proof and finished the chapter. In the end I wrote the same proof, and it is working fine. <br>
If you want to replicate this behaviour then you just copy the whole Induction.v file, remove the comments in line 115 - 136 and press C-c C-return by keeping your cursor at line 136. I hope it will get stuck at line 115. I will try to reproduce this with shorter code. 
<br>
user@newport:~/Mukesh/Code/Coq/software-foundation-8.5$ uname -a
Linux newport 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
 of 2016-06-28 on newport    

-Mukesh Tiwari

[1] https://github.com/mukeshtiwari/Coq/blob/master/software-foundation-8.5/Induction.v

**Comment by bixuanzju** [comment] 2016-06-30 09:57
I can reproduce on my Mac with Coq 8.5. Deleting curly braces `{}` in line 120 would make the problem go away. Compiling this file is fine with `coqc` in the terminal, so I guess it's really about PG maybe.

**Comment by Matafou** [comment] 2016-07-01 08:31
Hi, does replacing ".}" by ". }" solve the problem?

If yes this is a (known) bug indeed.

Whereas coq should accept this or not is not clear to me (the end of
acommand should be a dot followed by a space, nothing else) but PG should
not hang on it anyway.

Not sure to solve this right now though.

Pierre

2016-06-30 11:57 GMT+02:00 Jeremy Bi <notifications@github.com>:

**Comment by Matafou** [comment] 2016-07-01 14:10
Actually coq should not compile the version with ".}". Can you confirm that separating the dot and the curly brace ".  }" fixes it? If yes I will close this bug, otherwise I can't reproduce it.

**Comment by cpitclaudel** [comment] 2016-07-01 14:56
Thanks for the report. I agree with @Matafou here.

For posterity, here's a minified example:

```
Goal True.
  {apply I.}
Qed.
```

With this example, as well as with the whole file, coqc rejects the file and says this:

```
$ /build/coq-8.5/bin/coqc test.v
File "./test.v", line 111, characters 44-45:
Syntax Error: Lexer: Undefined token
```

(line 111 is `{ intros m. rewrite mult_r_0. reflexivity.}`, since I had to remove a few things to make the file compile).

CoqIDE also rejects this file. @bixuanzju @mukeshtiwari, are you sure it actually compiles?

**Comment by Matafou** [comment] 2016-07-01 15:05
Maybe we should try to have an error instead of getting stuck. This is a problem that will arise very often I guess.

**Comment by cpitclaudel** [comment] 2016-07-01 15:42
I don't think it's really worth it; once we move to the new protocol, we'll get this fix as a side effect for free.

**Comment by bixuanzju** [comment] 2016-07-02 15:07
@cpitclaudel you are right, I do have a space after `.`

**Comment by cpitclaudel** [comment] 2016-07-02 15:10
Ok, makes sense. PG could be better at spotting that syntax error (instead of just hanging) and will be once we migrate to the new protocol. I'll close this issue then :) Feel free to comment further if I missed something.

**Closed by cpitclaudel** 2016-07-02 15:10 UTC

**Comment by mukeshtiwari** [comment] 2016-07-04 00:59
@cpitclaudel  Sorry I was out for weekend so could not reply you.
