### ISSUE TITLE
idtac output is getting parsed by PG as commands

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#90] opened 2016-07-12 20:12 UTC
Goal True.
idtac "Require Dummy".

prints this, and messes up my PG windows:

-*- mode: compilation; -*-

echo "Require Dummy." > /tmp/ProofGeneral-coq17918FT.v /usr/local/bin/coqdep -Q /home/jil/coq/ "" /tmp/ProofGeneral-coq17918FT.v
*** Warning: in file /tmp/ProofGeneral-coq17918FT.v, library Dummy is required and has not been found in the loadpath!
*** Warning: in file /tmp/ProofGeneral-coq17918FT.v, library Dummy is required and has not been found in the loadpath!
/tmp/ProofGeneral-coq17918FT.vo /tmp/ProofGeneral-coq17918FT.glob /tmp/ProofGeneral-coq17918FT.v.beautified: /tmp/ProofGeneral-coq17918FT.v
/tmp/ProofGeneral-coq17918FT.vio: /tmp/ProofGeneral-coq17918FT.v

**Comment by cpitclaudel** [comment] 2016-07-12 21:51
Thanks a bug with compile-on-require, I think. @hendriktews ?

**Comment by Matafou** [comment] 2016-07-13 08:13
We had the same kind of problem with comments I remember.
P

Le mardi 12 juillet 2016, Clément Pit--Claudel <notifications@github.com> a
écrit :

**Comment by hendriktews** [comment] 2016-07-15 19:55
Yes, this looks like the regular expression that is searching for require commands is wrong.

**Comment by hendriktews** [comment] 2016-10-27 07:12
This is a duplicate of #75

**Closed by hendriktews** 2016-10-27 07:12 UTC
Labels: duplicate

**Comment by hendriktews** [comment] 2016-10-28 08:48
should be fixed by commit 3b621d71274bc62722876c7229c2e649be6cb378, please try.
