### ISSUE TITLE
after proof-layout-windows there is no decicated window left

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#122] opened 2016-10-28 17:52 UTC
When I do proof-layout-windows (C-c C-l) in 3-window mode then no window is dedicated any more (do M-: (window-dedicated-p) to find out). The sizes of the goals and response buffers do change as well. Is that intended?

**Comment by Matafou** [comment] 2016-11-03 10:01
I don't think the no-dedicatd is intended. But sizes of buffers should change to addapt to the height of output.

**Comment by hendriktews** [comment] 2016-11-03 11:03
What happens here is the C-c C-l enlarges a completely empty response buffer.

**Comment by Matafou** [comment] 2016-11-03 11:41
If there is nothing in response too then it may be the expected behaviour (though not the only possible one :)).

Concerning dedicated mode this looks like a bug. But we should decide if we want it solved or not. It is very annoying to have a bug in layout and not being able to switch back to the scripting buffer with C-x b. Hitting C-c C-l may solve the propblem but is resets widows positions and it is also sometime annoying.

Again windows layout is difficult because users want to have all emacs frames facilities while not missing any prover output...

**Comment by hendriktews** [comment] 2016-11-03 12:05
> But we should decide if we want it solved or not. It is very

Sure. I only submit these 3-window-mode issues in order to see
whether those are really a problem.

**Comment by Matafou** [comment] 2017-01-12 16:31
This seems to be fixed by commit af30e1ef04 fixing #121. Please reopen if it is not the case.

**Closed by Matafou** 2017-01-12 16:31 UTC
