### ISSUE TITLE
cannot use PG with trunk version of coq: Invalid version syntax: 'trunk'

### ISSUE THREAD

**Issue by jonleivent** [ProofGeneral/PG#93] opened 2016-07-16 15:01 UTC

**Comment by cpitclaudel** [comment] 2016-07-16 15:13
Is this a duplicate of #70?

**Comment by jonleivent** [comment] 2016-07-16 15:26
Quite possibly.  Sorry - I should have seen that and tested the compile-before-require option...

However, I have to abandon trunk for other reasons - I'm switching back to 8.5pl2...

**Comment by cpitclaudel** [comment] 2016-07-16 16:08
No problem. This bug just needs to get fixed on the Coq side.

**Closed by cpitclaudel** 2016-07-16 16:08 UTC
