### ISSUE TITLE
weird delay  

### ISSUE THREAD

**Issue by lczch** [ProofGeneral/PG#63] opened 2016-03-04 11:56 UTC
When I press "Enter" key exactly after the last `end.` of below code, annoying delay appears.
If I hold Enter for a while, delay accumulates. 
```
Ltac hehe H := clear H; intro H; simpl in H.
(** BUG: pg indentation, if replace hehe in chop_join with its sentence,
    weird action appears.
 **)

Ltac chop_join H :=
  (** H: hypo ident **)
  (** H has the form [H: join_list lz z], calculate the most primitive representation of z.
   **)
  let rec chop_join' l :=
      match l with
        | nil => idtac
        | ?x :: ?l' =>
          match goal with
            | H': join_list ?lx x |- _ =>
              chop_join H'; (** make H' to be the most primitive form **)
              liftH H x; 
              generalize (@jl_sub _ _ _ _ _ _ _ H' _ H); (** subst x with lx' in H' **)
              hehe H;
              chop_join' l'
            | _ => chop_join' l'
          end
      end in
  match type of H with
    | join_list ?lx ?x =>
      let b := check_done x in
      match b with
        | true => idtac 
        | false =>
          place_done x;
          let l1 := constr:(rev lx) in
          let l2 := (eval simpl in l1) in
          chop_join' l2
      end
  end.
```
Emacs version: 24.5
PG version: the latest master branch

I test this problem with a clean emacs with only PG, and the problem exists.
Some other problem is about pg's indentation of coq.
As comment in the code, if I replace `hehe` in `chop_join` with `clear H; intro H; simpl in H;`,
then the indentation of the next line is obviously incorrect.
It become:

```
Ltac chop_join H :=
  (** H: hypo ident **)
  (** H has the form [H: join_list lz z], calculate the most primitive representation of z.
   **)
  let rec chop_join' l :=
      match l with
        | nil => idtac
        | ?x :: ?l' =>
          match goal with
            | H': join_list ?lx x |- _ =>
              chop_join H'; (** make H' to be the most primitive form **)
              liftH H x; 
              generalize (@jl_sub _ _ _ _ _ _ _ H' _ H); (** subst x with lx' in H' **)
              clear H; intro H; simpl in H;
                                     chop_join' l'
| _ => chop_join' l'
end
...
```

**Comment by Matafou** [comment] 2016-03-08 10:34
Hi, thanks for reporting.

I see the indentation bug (pg believes the "in" corresponds to the let above, will try to fix).

but I don't see the slowdown. Is it slow when this code is at the start of a file?

P.

**Comment by lczch** [comment] 2016-03-08 11:12
No, this code can be anywhere in a file, and the slowdown appears.
But the slowdown is more evident if pressing **return** for a while, for example, pressing it for 3 sec.
I test it again with a clean emacs, with copy above code to a new file,  then the slowdown always appears.
Only when cursor is just after `end`, and press **return**, the problem emerges.
For example (| indicate cursor):

```
Ltac chop_join H :=
  (** H: hypo ident **)
  (** H has the form [H: join_list lz z], calculate the most primitive representation of z.
   **)
  let rec chop_join' l :=
      match l with
        | nil => idtac
        | ?x :: ?l' =>
          match goal with
            | H': join_list ?lx x |- _ =>
              chop_join H'; (** make H' to be the most primitive form **)
              liftH H x; 
              generalize (@jl_sub _ _ _ _ _ _ _ H' _ H); (** subst x with lx' in H' **)
              hehe H;
              chop_join' l'
            | _ => chop_join' l'
          end
      end in
  match type of H with
    | join_list ?lx ?x =>
      let b := check_done x in
      match b with
        | true => idtac 
        | false =>
          place_done x;
          let l1 := constr:(rev lx) in
          let l2 := (eval simpl in l1) in
          chop_join' l2
      end
  end.|
```
If I type some thing after `end.`, and press **return**, no problems.

**Comment by Matafou** [comment] 2016-03-08 12:53
The indentation error seems difficult to fix (there are plenty of diferent uses of "in" in coq syntax and it is almost impossible to know which one except by asking coq itself).

Meanwhile you can put parenthesis around (simpl in H). This forces "in" to be recognized as not part of the let.

Concerning the slowdown, I can't reproduce. Which version of PG are you using please?

**Comment by Matafou** [comment] 2016-03-08 14:00
I don't see how to deambiguate the "in" token for indentation. I won't fix this until we can ask coq itself this kind of information. As a workaround one should always try to add parenthesis to help the pg smie lexer to "jump" parenthesized blocks.

**Comment by Matafou** [comment] 2016-03-08 14:01
Concerning the delay can someone else try to reproduce the bug please?

**Comment by cpitclaudel** [comment] 2016-03-08 14:08
I can reproduce the delay in Emacs 25 on PG's master branch. Here's a profile:

```
- command-execute                                                4210  97%
 - call-interactively                                            4210  97%
  - apply                                                        4210  97%
   - ad-Advice-call-interactively                                4210  97%
    - #<subr call-interactively>                                 4202  97%
     - funcall-interactively                                     4202  97%
      - newline                                                  4015  93%
       - self-insert-command                                     4015  93%
        - electric-indent-post-self-insert-function               3983  92%
         - indent-according-to-mode                              3983  92%
          - smie-indent-line                                     3983  92%
           - smie-indent-calculate                               3983  92%
            - run-hook-with-args-until-success                   3983  92%
             - smie-indent-after-keyword                         3979  92%
              - smie-indent-virtual                              3887  90%
               - smie-indent-calculate                           3887  90%
                - run-hook-with-args-until-success               3887  90%
                 - smie-indent-keyword                           3883  90%
                  - smie-backward-sexp                           3794  88%
                   - smie-next-sexp                              3794  88%
                    - #<lambda 0x1fc97c3a3780>                   3646  84%
                     - let*                                      3646  84%
                      - coq-smie-is-tactic                       1794  41%
                       - save-excursion                          1794  41%
                        - coq-find-real-start                    1770  41%
                         - coq-find-current-start                1694  39%
                          - coq-script-parse-cmdend-backward               1686  39%
                           - proof-buffer-syntactic-context                164   3%
                              syntax-ppss                         128   2%
                           - coq-skip-until-one-comment-backward                 40   0%
                              coq-search-comment-delimiter-backward                 32   0%
                             coq-is-on-ending-context                  4   0%
                         - coq-find-not-in-comment-forward                 56   1%
                          - coq-looking-at-comment                 40   0%
                           - proof-inside-comment                  40   0%
                            - proof-buffer-syntactic-context                 36   0%
                               syntax-ppss                         28   0%
                          - coq-skip-until-one-comment-forward                  8   0%
                             coq-search-comment-delimiter-forward                  4   0%
                        - let                                       4   0%
                           not                                      4   0%
                      - save-excursion                           1680  38%
                       - coq-find-real-start                     1680  38%
                        - coq-find-current-start                 1556  36%
                         - coq-script-parse-cmdend-backward               1532  35%
                          - proof-buffer-syntactic-context                132   3%
                             syntax-ppss                          108   2%
                          - coq-skip-until-one-comment-backward                 36   0%
                             coq-search-comment-delimiter-backward                 36   0%
                        - coq-find-not-in-comment-forward                 96   2%
                         - coq-looking-at-comment                  60   1%
                          - proof-inside-comment                   56   1%
                           - proof-buffer-syntactic-context                 48   1%
                              syntax-ppss                          36   0%
                         - coq-skip-until-one-comment-forward                 12   0%
                            coq-search-comment-delimiter-forward                  8   0%
                      - cond                                      136   3%
                       - save-excursion                           100   2%
                        - let                                     100   2%
                         - coq-smie-search-token-backward                100   2%
                          - condition-case                        100   2%
                           - catch                                100   2%
                            - while                               100   2%
                             - let*                                96   2%
                              - coq-dot-friend-p                   24   0%
                               - and                               24   0%
                                  not                               4   0%
                                smie-default-backward-token                 24   0%
                              - if                                 20   0%
                               - if                                16   0%
                                - progn                            12   0%
                                   cond                            12   0%
                       - let                                        8   0%
                        - if                                        8   0%
                         - if                                       8   0%
                          - save-excursion                          8   0%
                           - coq-smie-.-deambiguate                  8   0%
                            - save-excursion                        8   0%
                             - let                                  8   0%
                              - cond                                4   0%
                                 or                                 4   0%
                                coq-find-real-start                  4   0%
                       - and                                        4   0%
                          looking-back                              4   0%
                       - coq-dot-friend-p                           4   0%
                          and                                       4   0%
                        smie-default-backward-token                 12   0%
                    - #<compiled 0x14c6ecf>                       144   3%
                     - backward-sexp                              144   3%
                      - forward-sexp                              144   3%
                       - smie-forward-sexp-command                144   3%
                        - smie-backward-sexp                      144   3%
                         - smie-next-sexp                         144   3%
                          - #<lambda 0x1fc97c3a3780>                144   3%
                           - let*                                 144   3%
                            - coq-smie-is-tactic                   96   2%
                             - save-excursion                      96   2%
                              - coq-find-real-start                 96   2%
                               - coq-find-current-start                 96   2%
                                - coq-script-parse-cmdend-backward                 96   2%
                                 - coq-skip-until-one-comment-backward                  4   0%
                                    coq-search-comment-delimiter-backward                  4   0%
                                 - proof-buffer-syntactic-context                  4   0%
                                    syntax-ppss                     4   0%
                            - save-excursion                       48   1%
                             - coq-find-real-start                 48   1%
                              - coq-find-current-start                 44   1%
                               - coq-script-parse-cmdend-backward                 40   0%
                                - proof-buffer-syntactic-context                  8   0%
                                   syntax-ppss                      8   0%
                              - coq-find-not-in-comment-forward                  4   0%
                                 coq-skip-until-one-comment-forward                  4   0%
                  - smie-indent-forward-token                      89   2%
                   - coq-smie-forward-token                        89   2%
                    - let                                          89   2%
                     - cond                                        89   2%
                      - cond                                       89   2%
                       - save-excursion                            89   2%
                        - coq-smie-backward-token                  89   2%
                         - let*                                    89   2%
                          - save-excursion                         40   0%
                           - coq-find-real-start                   40   0%
                            - coq-find-current-start                 40   0%
                               coq-script-parse-cmdend-backward                 40   0%
                          - cond                                   27   0%
                           - let                                   27   0%
                            - if                                   27   0%
                             - if                                  27   0%
                              - save-excursion                     27   0%
                               - coq-smie-.-deambiguate                 27   0%
                                - save-excursion                   27   0%
                                 - let                             27   0%
                                  - coq-find-real-start                 20   0%
                                   - coq-find-current-start                 20   0%
                                    - coq-script-parse-cmdend-backward                 20   0%
                                       proof-buffer-syntactic-context                  4   0%
                                  - cond                            7   0%
                                   - or                             7   0%
                                    - coq-smie-detect-goal-command                  7   0%
                                     - save-excursion                  7   0%
                                      - if                          7   0%
                                         proof-looking-at                  3   0%
                          - coq-smie-is-tactic                     22   0%
                           - save-excursion                        22   0%
                            - coq-find-real-start                  22   0%
                             - coq-find-current-start                 22   0%
                                coq-script-parse-cmdend-backward                 22   0%
                 - smie-indent-inside-string                        4   0%
                    syntax-ppss                                     4   0%
              - smie-indent-backward-token                         92   2%
               - coq-smie-backward-token                           92   2%
                - let*                                             92   2%
                 - save-excursion                                  60   1%
                  - coq-find-real-start                            60   1%
                   - coq-find-current-start                        48   1%
                    - coq-script-parse-cmdend-backward                 48   1%
                     - proof-buffer-syntactic-context                  4   0%
                        syntax-ppss                                 4   0%
                   - coq-find-not-in-comment-forward                 12   0%
                    - coq-looking-at-comment                        8   0%
                     - proof-inside-comment                         4   0%
                      - proof-buffer-syntactic-context                  4   0%
                         syntax-ppss                                4   0%
                 - coq-smie-is-tactic                              20   0%
                  - save-excursion                                 20   0%
                   - coq-find-real-start                           20   0%
                    - coq-find-current-start                       20   0%
                       coq-script-parse-cmdend-backward                 20   0%
                 - cond                                            12   0%
                  - let                                            12   0%
                   - if                                            12   0%
                    - if                                           12   0%
                     - save-excursion                              12   0%
                      - coq-smie-.-deambiguate                     12   0%
                       - save-excursion                            12   0%
                        - let                                      12   0%
                         - coq-find-real-start                     12   0%
                          - coq-find-current-start                 12   0%
                             coq-script-parse-cmdend-backward                 12   0%
             - smie-indent-keyword                                  4   0%
              - smie-indent-forward-token                           4   0%
               - coq-smie-forward-token                             4   0%
                - let                                               4   0%
                 - cond                                             4   0%
                    and                                             4   0%
        - smie-blink-matching-open                                 32   0%
         - coq-smie-backward-token                                 32   0%
          - let*                                                   32   0%
           - cond                                                  20   0%
            - let                                                  20   0%
             - if                                                  20   0%
              - if                                                 20   0%
               - save-excursion                                    20   0%
                - coq-smie-.-deambiguate                           20   0%
                 - save-excursion                                  20   0%
                  - let                                            20   0%
                   - coq-find-real-start                           16   0%
                    - coq-find-current-start                       16   0%
                     - coq-script-parse-cmdend-backward                 16   0%
                        proof-buffer-syntactic-context                  4   0%
                   - cond                                           4   0%
                    - equal                                         4   0%
                     - coq-smie-module-deambiguate                  4   0%
                        save-excursion                              4   0%
           - coq-smie-is-tactic                                     8   0%
            - save-excursion                                        8   0%
             - coq-find-real-start                                  8   0%
              - coq-find-current-start                              8   0%
                 coq-script-parse-cmdend-backward                   8   0%
           - save-excursion                                         4   0%
            - coq-find-real-start                                   4   0%
             - coq-find-current-start                               4   0%
                coq-script-parse-cmdend-backward                    4   0%
```

**Comment by Matafou** [comment] 2016-03-08 14:41
The only stange thing I see is the calls to coq-smie-is-tactic.
I just commited a removal of a call to this function. Please let me know if this makes things better.

**Comment by lczch** [comment] 2016-03-09 11:18
Unfortunately, the slowdown is still obvious.
 @cpitclaudel You profile is so cool, How can you produce it ?

**Comment by lczch** [comment] 2016-03-09 11:28
this is my profile:
```
- command-execute                                                2249  93%
 - call-interactively                                            2249  93%
  - newline                                                      2048  84%
   - self-insert-command                                         2048  84%
    - electric-indent-post-self-insert-function                  2036  84%
     - indent-according-to-mode                                  2036  84%
      - smie-indent-line                                         2036  84%
       - funcall                                                 2036  84%
        + #<compiled 0xbfcb33>                                   2036  84%
    + smie-blink-matching-open                                     12   0%
  + byte-code                                                     161   6%
  + minibuffer-complete                                            36   1%
  + execute-extended-command                                        4   0%
+ ...                                                             167   6%

```
The problem may be about `smie-indent-line`.

**Comment by Matafou** [comment] 2016-03-09 15:37
OK I managed to reproduce in a fresh pg config, and it seems to come from  coq-one-command-per-line that is t by default (indentation done after each newline).

I think I fixed it. Please test.
P.

**Closed** 2016-03-09 15:36 UTC
Labels: wontfix

**Comment by lczch** [comment] 2016-03-10 05:26
I have tested it, the fix is working:)
Thanks~

**Comment by cpitclaudel** [comment] 2016-03-10 15:01
Great, thanks Pierre!
